# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: build
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.3.1
      with:
        dotnet-version: |
          9.0.x
          8.0.x
    - name: Install dependencies
      run: dotnet restore SpreadsheetLight.csproj
    - name: Build
      run: dotnet build SpreadsheetLight.csproj --configuration Release
